config/routes.rb
Rails.application.routes.draw do
  resources :requisitions, except: [:destroy]
  resources :profiles, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }

  root to: 'home#index'
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user

  validates :first_name, presence: true
  validates :first_last_name, presence: true
  validates :curp, presence: true, length: { is: 18 }
  validates :rfc, presence: true, length: { is: 13 }
  validates :birth_date, presence: true
  validates :gender, presence: true
  validates :phone_number, presence: true, format: { with: /\A[\d-]*\z/, message: "eg: 33-333-3333" }


end

app/models/requisition.rb
class Requisition < ActiveRecord::Base

  belongs_to :user

  scope :my_requisitions, -> (user_id){ where(user_id: user_id) }

  validates :income,        presence: true, numericality: { greater_than: 0 }
  validates :address_years, presence: true, numericality: { only_integer: true }
  validates :company_years, presence: true, numericality: { only_integer: true }
  validates :requested_amount, presence: true, numericality: { greater_than: 0 }
  validates :payment_terms, presence: true, numericality: { only_integer: true }
  validates :bank, presence: true
  validates :company_name, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_one :profile
  has_many :requisitions


  def self.from_omniauth(data)
    where(provider: data[:provider], uid: data[:uid]).first_or_create do |user|
      user.email = data[:email]
      user.password = Devise.friendly_token[0, 20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  def after_sign_in_path_for(resource)
    resource.profile.present? ? requisitions_path : new_profile_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authenticate_user!

  def index
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      flash[:notice] = 'Updated profile'
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:first_name,
                                    :second_name,
                                    :second_last_name,
                                    :first_last_name,
                                    :birth_date,
                                    :curp,
                                    :rfc,
                                    :gender,
                                    :birth_state,
                                    :phone_number
    )
  end

end

app/controllers/requisitions_controller.rb
class RequisitionsController < ApplicationController

  def new
    @requisition = Requisition.new
  end

  def create
    @requisition = current_user.requisitions.build(requisition_params)
    if @requisition.save
      redirect_to requisitions_path
    else
      render :new
    end
  end

  def index
    @requisitions = current_user.requisitions
  end

  def show
    @requisition = Requisition.where(user_id: current_user.id, id: params[:id]).first
  end

  def edit
    @requisition = Requisition.where(user_id: current_user.id, id: params[:id]).first
  end

  def update
    @requisition = Requisition.where(user_id: current_user.id, id: params[:id]).first
    if @requisition.update(requisition_params)
      flash[:notice] = 'Changes saved'
      redirect_to @requisition
    else
      render :edit
    end
  end

  private

  def requisition_params
    params.require(:requisition).permit(
      :income,
      :address_years,
      :company_years,
      :marital_status,
      :requested_amount,
      :payment_terms,
      :bank,
      :comment,
      :company_name,
      :company_phone_number,
      :dependents_number,
      :company_position,
      :has_sgmm,
      :has_imss,
      :has_car
    )
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    data = OauthFormatter.call(data: request.env['omniauth.auth'])

    unless data.success?
      flash[:error] = "Something went wrong"
      redirect_to root_path
      return
    end

    session['profile_data'] = data.profile_data

    @user = User.from_omniauth(data.user_data)

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

  protected

  def after_sign_in_path_for(resource)
    if resource.profile
      requisitions_path
    else
      new_profile_path
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def new
    redirect_to root_path
  end

  def destroy
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_for_navbar
    if current_user
      current_user.profile.present? ? requisitions_path : root_path
    else
      root_path
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper

  def genders_list
    {
      I18n.t('genders.male') => 'M',
      I18n.t('genders.female') => 'F',
    }
  end
end

app/views/home/index.html.haml
.row
  .col-md-offset-1.col-md-10
    .jumbotron
      %h1.display-4 Requisition
      %p.lead
        The best place for getting the requisition that you need.
      %hr.my-4
        Join us for getting a lot of benefits
      %p.lead
        = link_to 'Facebook login', user_facebook_omniauth_authorize_path, class: 'btn btn-primary btn-large'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Requisitions
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %a.navbar-brand{ href: link_for_navbar } Requisitions
        - if current_user
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-large'
    .container{ role: 'main'}
      - if notice.present?
        %p.notice= notice
      - if alert.present?
        %p.alert= alert
      = yield

      = content_for :javascript_onbody

app/views/profiles/new.html.haml
%h2 Profile
.row
  .col-md-8
    = simple_form_for @profile, url: profiles_path, method: :post do |f|
      = f.input :first_name, input_html: { value: session['profile_data']['first_name'] }
      = f.input :second_name
      = f.input :first_last_name, input_html: { value: session['profile_data']['last_name'] }
      = f.input :second_last_name
      = f.input :gender, collection: genders_list, prompt: 'Select an option'
      = f.input :birth_date, start_year: Date.today.year - 90, end_year: Date.today.year - 18
      = f.input :curp
      = f.input :rfc
      = f.input :birth_state, collection: t('states'), prompt: 'Select an option'
      = f.input :phone_number
      = f.submit 'Save',  class: 'btn btn-default btn-large'

app/views/requisitions/_form.html.haml
= f.input :income
= f.input :address_years
= f.input :marital_status, collection: t('marital_status_list'), prompt: 'Select an option'
= f.input :dependents_number
= f.input :company_name
= f.input :company_years
= f.input :company_phone_number
= f.input :requested_amount
= f.input :payment_terms, collection: t('payment_terms_list'), prompt: 'Select an option'
= f.input :bank
= f.input :comment
= f.input :has_sgmm
= f.input :has_imss
= f.input :has_car

app/views/requisitions/edit.html.haml
%h2 Modify requisition
.row
  .col-md-8
    = simple_form_for @requisition, url: requisition_path, method: :put do |f|
      = render partial: 'form', locals: { f: f }
      = f.submit 'Save changes', class: 'btn btn-default btn-large'

app/views/requisitions/index.html.haml
%h2 Requisitions

.row
  .col-md-4
    = link_to 'New requisition', new_requisition_path, class: 'btn btn-primary btn-large'
%table.table
  %thead
    %th °N
    %th Requested amount
    %th Payment terms
    %th Bank
    %th Actions
  %tbody
    - @requisitions.each do |requisition|
      %tr
        %td= requisition.id
        %td= number_to_currency(requisition.requested_amount)
        %td= requisition.payment_terms
        %td= requisition.bank
        %td
          = link_to 'View', requisition_path(id: requisition.id)
          = link_to 'Modify', edit_requisition_path(id: requisition.id)

app/views/requisitions/new.html.haml
%h2 New requisition
.row
  .col-md-8
    = simple_form_for @requisition, url: requisitions_path, method: :post do |f|
      = render partial: 'form', locals: { f: f }
      = f.submit 'Generate requisition', class: 'btn btn-default btn-large'

app/views/requisitions/show.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title= "Requisition #{ @requisition.id }"
  .panel-body
    .panel

      - @requisition.attributes.except('id', 'user_id', 'created_at', 'updated_at').each do |k,v|
        .row
          .col-md-4
            = t("activerecord.attributes.requisition.#{k}")
          .col-md-8
            = ['income', 'requested_amount'].include?(k) ? number_to_currency(v) : v
      .row
        .col-md-4
          = link_to 'Modify', edit_requisition_path(id: @requisition.id), class: 'btn btn-default btn-large'
        .col-md-4
          = link_to 'Back', requisitions_path, class: 'btn btn-default btn-large'